//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMvcAsp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User1
    {
        public int UserId { get; set; }
        [DisplayName("User Name")] //display name on the view
        public string UserName { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Password")]
        public string Paswword { get; set; }
    }
}
